--- 
javascripts: 

- base-cached:
  - lowpro.jquery
  - eol
  - search
  - comments
  - admin
  - misc
  - builder
  - bioGUIDv3
  - application 

- taxa-page-cached:
  - tagging
  - curation
  - rating
  - text_objects
  - media_center
  - popup

- jquery-extras-cached:
  - jquery-autocomplete
  - jquery.scrollTo-min
  - jquery.qtip-1.0.0-rc3.min

stylesheets: 
- base-cached: 
  - main
  - popup
  - taxa_comments
  - reset-min
  - tags
