--- 
javascripts: 

- base-cached:
  - jquery.tools.min
  - eol
  - search
  - comments
  - builder
  - bioGUIDv3
  - application 

- taxa-page-cached:
  - rating
  - media_center
  - popup
  - navigation

- jquery-extras-cached:
  - jquery-autocomplete
  - jquery.qtip-1.0.0-rc3.min
  - tagging

stylesheets: 
- base-cached: 
  - main
  - popup
  - taxa_comments
  - reset-min
  - tags
