--- 
javascripts: 

- base-cached:
  - flashobjects
  - eol
  - tagging
  - search
  - curation
  - comments
  - admin
  - rating
  - text_objects
  - media_center
  - popup
  - misc
  - validator
  - faqs
  - builder
  - flash_detect_min
  - jsonbioGUIDv3
  - application 

- jquery-extras-cached:
  - jquery-autocomplete
  - jquery.scrollTo-min
  - jquery.qtip-1.0.0-rc3.min

stylesheets: 
- base-cached: 
  - main
  - popup
  - taxa_comments
  - reset-min
  - tags
