--- 
javascripts: 

- base-cached:
  - jquery.tools.min
  - eol
  - search
  - bioGUIDv3
  - application 

- taxa-page-cached:
  - rating
  - media_center
  - popup
  - navigation
  - swfobject
  - wiki_ogg_player

- jquery-extras-cached:
  - jquery-autocomplete
  - tagging

stylesheets: 
- base-cached: 
  - main
  - popup
  - taxa_comments
  - reset-min
  - tags
