# Common settings for all databases.
common: &common
  adapter: mysql2
  encoding: utf8
  reconnect: true
  # socket: /var/run/mysql2d/mysql2d.sock

# Common settings for development databases.
devel_common: &dev
  host: localhost
  username: root
  password: 

# Common settings for test databases.
tst_common: &tst
  host: localhost
  username: root
  password: 

# Common settings for integration, staging and production databases.
# Note this is an example file, in reality production databases should be on a
# separate host.
int_common: &remote
  host: remote.example.com
  username: user
  password: password


# == Development environment databases
development:
  <<: *common
  <<: *dev
  database: eol_development

development_data:
  <<: *common
  <<: *dev
  database: eol_data_development

development_logging:
  <<: *common
  <<: *dev
  database: eol_logging_development

# == Test environment databases
# Support for read/write splitting is included in the application and is tested
# using master/slave databases in the test environment.
test:
  <<: *common
  <<: *tst
  database: eol_test

test_data:
  <<: *common
  <<: *tst
  database: eol_data_test

test_logging:
  <<: *common
  <<: *tst
  database: eol_logging_test

test_master:
  <<: *common
  <<: *tst
  database: eol_test_master

test_master_data:
  <<: *common
  <<: *tst
  database: eol_data_test_master

test_master_logging:
  <<: *common
  <<: *tst
  database: eol_logging_test_master

# == Integration environment databases
integration:
  <<: *common
  <<: *remote
  database: eol_integration

integration_data:
  <<: *common
  <<: *remote
  database: eol_data_integration

integration_logging:
  <<: *common
  <<: *remote
  database: eol_logging_production

# == Staging environment databases
staging:
  <<: *common
  <<: *remote
  database: eol_staging

staging_data:
  <<: *common
  <<: *remote
  database: eol_data_staging

staging_logging:
  <<: *common
  <<: *remote
  database: eol_logging_production

# == Production environment databases
master_database:
  <<: *common
  <<: *remote
  database: eol_integration

master_data_database:
  <<: *common
  <<: *remote
  database: eol_data_integration

master_logging_database:
  <<: *common
  <<: *remote
  database: eol_logging_production
