# There are two databases for each environment, plus one for the MySQL master 
# in production.
#
# 1. The Rails database
# 2. The EOL species database. Writing is not allowed to this database
# 3. The master_database connection is used in production mode. It is the 
#    database master for writes for the standard Rails database
#
# For developers:
# 1. Make sure to setup your +development+ and +test+ environments
# 2. During development, the "_data" databases should share the same name, 
#    e.g. eol_data_shared. This is because the "denormal:build_random_taxa"
#    rake task populates it with actual data useful for testing and dev.
# 
# Common settings for each environment assume that all four databases are on 
# the same database server for each environment.  If this is not the case, 
# you will need to manually edit the entries below the +common+ settings for 
# each database in that environment.
#
# The convention for database names is "eol_<DATABASENAME>_<RAILS_ENV>"
# common settings for all production databases

#######################
development:
  adapter: mysql
  encoding: utf8
  host:     localhost
  username: root
  password:
  database: eol_development
  
development_data:
  adapter: mysql
  encoding: utf8
  host:     localhost
  username: root
  password:
  database: eol_data_development

development_logging:
  adapter: mysql
  encoding: utf8
  host:     localhost
  username: root
  password:
  database: eol_logging_development

############################
test:
  adapter: mysql
  encoding: utf8
  host:     localhost
  username: root
  password:
  database: eol_test

test_data:
  adapter: mysql
  encoding: utf8
  host:     localhost
  username: root
  password:
  database: eol_data_test

test_logging:
  adapter: mysql
  encoding: utf8
  host:     localhost
  username: root
  password:
  database: eol_logging_test

############################
demo:
  adapter: mysql
  encoding: utf8
  host:     localhost
  username: username
  password: password
  database: eol_demo
  
demo_data:
  adapter: mysql
  encoding: utf8
  host:     localhost
  username: username
  password: password
  database: eol_data_demo

demo_logging:
  adapter: mysql
  encoding: utf8
  host:     localhost
  username: username
  password: password
  database: eol_logging_demo

############################    
integration:
  adapter: mysql
  encoding: utf8
  host:     localhost
  username: username
  password: password
  database: eol_integration

integration_data:
  adapter: mysql
  encoding: utf8
  host:     localhost
  username: username
  password: password
  database: eol_data_integration
  
integration_logging:
  adapter: mysql
  encoding: utf8
  host:     localhost
  username: username
  password: password
  database: eol_logging_integration
############################  
production:
  adapter: mysql
  encoding: utf8
  host:     mdata.example.org
  username: username
  password: password
  database: eol_production

production_data:
  adapter: mysql
  encoding: utf8
  host:     mdata.example.org
  username: username
  password: password
  database: eol_data_production

production_logging:
  adapter: mysql
  encoding: utf8
  host:     mdata.example.org
  username: username
  password: password
  database: eol_logging_production
  
############################  
# for production only
# master database connection for rails database
#master_database:
#  <<: *common
#  <<: *development_common
#  database: eol_development
#
# master database connection for data database  
#master_data_database:
#  <<: *common
#  <<: *development_common
#  database: eol_data_development
